/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package buscaminas.paneles;

import buscaminas.utiles.LectorProperties;
import javax.swing.ImageIcon;

/**
 *
 * @author Juan
 */
public class RecordPanel extends javax.swing.JFrame {

    //Objeto LectorPropiedades, automáticamente carga los valores properties
    LectorProperties propiedades = new LectorProperties();
    
    //Método para formatear el tiempo
    public String getTiempoFormateado(Long tiempoLong){
        String tiempo = String.valueOf(tiempoLong);
        String segundos = String.valueOf(tiempoLong/1000);
        String milisegundos = tiempo.substring(segundos.length(), segundos.length()+2);
        return segundos+"´"+milisegundos+"seg";
    } 
    //Método para mostrar los valores correspondientes en cada jLabel
    public void showData(){
        jLabelPrincipiante.setText(propiedades.getNombrePrincipiante());
        jLabelIntermedio.setText(propiedades.getNombreIntermedio());
        jLabelAvanzado.setText(propiedades.getNombreAvanzado());
        jLabelTiempoPrincipiante.setText(getTiempoFormateado(propiedades.getTiempoPrincipiante()));
        jLabelTiempoIntermedio.setText(getTiempoFormateado(propiedades.getTiempoIntermedio()));
        jLabelTiempoAvanzado.setText(getTiempoFormateado(propiedades.getTiempoAvanzado()));
    }
    
    //Método reestablecer valores
    public void resetData(){
        String nombre = "Anonimo";
        Long tiempo = (long)999999;
        propiedades.setNombrePrincipiante(nombre);
        propiedades.setNombreIntermedio(nombre);
        propiedades.setNombreAvanzado(nombre);
        propiedades.setTiempoPrincipiante(tiempo);
        propiedades.setTiempoIntermedio(tiempo);
        propiedades.setTiempoAvanzado(tiempo);
        propiedades.storeProperties();
    }
    
    public RecordPanel() {
        initComponents();
        //Centrarlo
        this.setLocationRelativeTo(null);
         //Icono de la ventana
        setIconImage(new ImageIcon(getClass().getResource("/images/records.png")).getImage());
        this.showData();
        //Hacerlo visible
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelPrincipiante = new javax.swing.JLabel();
        jLabelIntermedio = new javax.swing.JLabel();
        jLabelAvanzado = new javax.swing.JLabel();
        jLabelTiempoPrincipiante = new javax.swing.JLabel();
        jLabelTiempoIntermedio = new javax.swing.JLabel();
        jLabelTiempoAvanzado = new javax.swing.JLabel();
        jButtonReiniciar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Records");

        jLabel1.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("idiomas/string"); // NOI18N
        jLabel1.setText(bundle.getString("record_principiante")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel2.setText(bundle.getString("record_intermedio")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Consolas", 1, 14)); // NOI18N
        jLabel3.setText(bundle.getString("record_avanzado")); // NOI18N

        jLabelPrincipiante.setText("jLabel4");

        jLabelIntermedio.setText("jLabel4");

        jLabelAvanzado.setText("jLabel4");

        jLabelTiempoPrincipiante.setText("jLabel4");

        jLabelTiempoIntermedio.setText("jLabel4");

        jLabelTiempoAvanzado.setText("jLabel4");

        jButtonReiniciar.setText(bundle.getString("reiniciar")); // NOI18N
        jButtonReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReiniciarActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/record.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelAvanzado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTiempoAvanzado))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelPrincipiante, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTiempoPrincipiante))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIntermedio, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelTiempoIntermedio)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReiniciar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabelPrincipiante)
                            .addComponent(jLabelTiempoPrincipiante))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabelIntermedio)
                            .addComponent(jLabelTiempoIntermedio))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelAvanzado)
                            .addComponent(jLabelTiempoAvanzado)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addGap(26, 26, 26)
                .addComponent(jButtonReiniciar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReiniciarActionPerformed
        //Se resetean los valores y se muestran
        this.resetData();
        this.showData();
    }//GEN-LAST:event_jButtonReiniciarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordPanel().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReiniciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelAvanzado;
    private javax.swing.JLabel jLabelIntermedio;
    private javax.swing.JLabel jLabelPrincipiante;
    private javax.swing.JLabel jLabelTiempoAvanzado;
    private javax.swing.JLabel jLabelTiempoIntermedio;
    private javax.swing.JLabel jLabelTiempoPrincipiante;
    // End of variables declaration//GEN-END:variables
}
